import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html>
      <head>
        <link 
        rel="preconnect" 
        href="https://fonts.googleapis.com"
        />
        
        <link 
        rel="preconnect" 
        href="https://fonts.gstatic.com" 
        crossOrigin="anonymous"
         />
        
        
        <link
        href="https://fonts.googleapis.com/css2?family=Noto+Sans&family=Noto+Serif&family=Roboto&family=Open+Sans&family=Zen+Kaku+Gothic+New&family=Zen+Old+Mincho&family=Sawarabi+Gothic&family=M+PLUS+1p&family=M+PLUS+Rounded+1c&family=Kosugi&family=Kosugi+Maru&display=swap" 
        rel="stylesheet"
        />

        
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
